import { google } from "googleapis";
import * as fs from "fs";
import * as path from "path";
import * as dotenv from "dotenv";

dotenv.config();

const CLIENT_ID = process.env.YOUTUBE_CLIENT_ID;
const CLIENT_SECRET = process.env.YOUTUBE_CLIENT_SECRET;
const REFRESH_TOKEN = process.env.YOUTUBE_REFRESH_TOKEN;

if (!CLIENT_ID || !CLIENT_SECRET || !REFRESH_TOKEN) {
  console.error("Missing YouTube OAuth credentials in .env file.");
  process.exit(1);
}

const oauth2Client = new google.auth.OAuth2(
  CLIENT_ID,
  CLIENT_SECRET,
  "http://localhost" // Redirect URL (not strictly needed for background upload using refresh token)
);

oauth2Client.setCredentials({ refresh_token: REFRESH_TOKEN });

const youtube = google.youtube({
  version: "v3",
  auth: oauth2Client,
});

const uploadVideo = async () => {
  const filePath = path.join(__dirname, "out", "video.mp4");

  if (!fs.existsSync(filePath)) {
    console.error(`Video file not found at ${filePath}. Please render the video first using 'npx remotion render'.`);
    process.exit(1);
  }

  const fileSize = fs.statSync(filePath).size;
  console.log(`Uploading ${filePath} (${(fileSize / 1024 / 1024).toFixed(2)} MB)...`);

  try {
    const res = await youtube.videos.insert({
      part: ["snippet", "status"],
      requestBody: {
        snippet: {
          title: "My Remotion PV",
          description: "Generated by Remotion PV Template",
          tags: ["remotion", "music", "pv"],
        },
        status: {
          privacyStatus: "unlisted", // 限定公開
        },
      },
      media: {
        body: fs.createReadStream(filePath),
      },
    });

    console.log("Upload successful!");
    console.log(`Video URL: https://www.youtube.com/watch?v=${res.data.id}`);
  } catch (error) {
    console.error("Error uploading video:");
    console.error(error);
  }
};

uploadVideo();